# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017" # maps container 27017 to local 27017
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
